apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: portfolio-website-deployment
spec:
  selector:
    matchLabels:
      app: portfolio-website
  template:
    metadata:
      labels:
        app: portfolio-website
    spec:
      containers:
        - name: portfolio-website-container
          image: gcr.io/everyones-happy/portfolio-website
          ports:
            - containerPort: 443
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-website-service
  labels:
    app: portfolio-website
spec:
  selector:
    app: portfolio-website
  ports:
    - port: 8080
      targetPort: 443
  type: NodePort
